// <autogenerated>
//   This file was generated by T4 code generator DtosCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using OSharp.Core.Data;
using System.ComponentModel.DataAnnotations;
using Bode.Services.Core.Models.User;

namespace Bode.Services.Core.Dtos.User
{
	public partial class UserInfoDto: IAddDto, IEditDto<int>
	{
        public System.Int32 Id { get; set; }
                            public System.String PhoneNo { get; set; }
                                        public System.String Password { get; set; }
                                        public System.String NickName { get; set; }
                                        public System.String HeadPic { get; set; }
                                        public System.DateTime BirthDay { get; set; }
                                        public System.String Signature { get; set; }
                                        public System.String RegistKey { get; set; }
                                        public Bode.Services.Core.Models.User.Sex Sex { get; set; }
                    	}
}
